"""Agregar columna api_key a tabla usuarios

Revision ID: 3927f6a9ee87
Revises: 9987107abff6
Create Date: 2026-07-16 00:34:22.663516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3927f6a9ee87'
down_revision = '9987107abff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_vault', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('lifecycle_events', schema=None) as batch_op:
        batch_op.alter_column('tech_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('observations',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_key')

    with op.batch_alter_table('lifecycle_events', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('observations',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('tech_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('document_vault', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.drop_table('tickets')
    # ### end Alembic commands ###
